### ISSUE TITLE
Can't install MKLSparse on Windows

### ISSUE THREAD

**Issue by ma-sadeghi** [JuliaSparse/MKLSparse.jl#14]
I installed `MKLSparse` on my Windows machine, but when `using MKLSparse` returns this error:

```
INFO: Precompiling module MKLSparse.
ERROR: LoadError: error compiling __init__: could not load library "libmkl_rt"
The specified module could not be found.
```

I've already installed MKL for Windows. I'd appreciate if you could elaborate on how to use the package.

**Comment by andreasnoack** [comment]
Have you set the environment variables with `mklvars.bat`?

**Comment by ma-sadeghi** [comment]
@andreasnoack I followed a guide I found on Intel's website, though I have no idea what it does :) I ran this command in `cmd`

```
mklvars intel64 mod
```

**Comment by andreasnoack** [comment]
You'd want to run
```
mklvars intel64 ilp64
```
from `cmd` and then launch julia from that `cmd` window.

**Comment by ma-sadeghi** [comment]
This time, `using MKLSparse` made more progress spitting out lots of deprecation warnings, but in the end I got this error
```
ERROR: InitError: error compiling __init__: could not load library "libmkl_rt"
The specified module could not be found.

Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:655
 [2] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:746
 [3] _require(::Base.PkgId) at .\loading.jl:956
 [4] require(::Base.PkgId) at .\loading.jl:878
 [5] require(::Module, ::Symbol) at .\loading.jl:873
during initialization of module MKLSparse
```

**Comment by RoyiAvital** [comment]
Will this work out of the box (Without installing MKL as standalone) with JulaiPro MKL Edition?

**Comment by Mango-3** [comment]
The problem under Windows comes from different naming conventions for libraries.
In Windows the libraries (.dll) don't have the lib-prefix, while in Linux they do. 
So you have to replace all library calls to libmkl_rt with the Windows version: mkl_rt

- Edit the file MKLSparse\src\MKLSparse.jl so that the MKL library call in line 6 is:
`ccall((:MKL_Set_Interface_Layer, :mkl_rt), Cint, (Cint,), Base.USE_BLAS64 ? 1 : 0)`
 
- Then replace all instances of `libmkl_rt` with `mkl_rt` in the file MKLSparse\src\BLAS\level_2_3\generator.jl

**Comment by KristofferC** [comment]
Thanks for the info, we should update that.

**Comment by Mango-3** [comment]
No problem @KristofferC After the changes it passes all tests:

![image](https://user-images.githubusercontent.com/22252558/42379218-b38e5412-8132-11e8-8032-83031fe38faa.png)

**Comment by KristofferC** [comment]
Should be fixed with the JLL
